LearnLog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('LearnLogs/',
         include(('LearnLogs.urls', 'LearnLogs'), namespace='LearnLogs')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

LearnLogs/urls.py
"""The URL configuration of LearnLogs"""

from django.urls import path
from . import views
# from django.conf.urls import url

urlpatterns = [
    # HomePage
    path('', views.index, name='index'),

    # The page shows the topics
    path('topics/', views.topics, name='topics'),

    # The page shows the entries of a topic
    path('topics/<topic_id>/', views.topic, name='topic'),
    # url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # The page is used to add new topic
    path('new_topic/', views.new_topic, name='new_topic'),

    # The page is used to add new entry
    path('new_entry/<topic_id>/', views.new_entry, name='new_entry'),

    # The page is used to edit an entry
    path('edit_entry/<entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

LearnLogs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    """The theme of the study"""
    text = models.CharField(max_length=200)
    date_added = models.DateField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return the string description of the model"""
        return self.text


class Entry(models.Model):
    """The knowledge of one studying topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:40] + "..."

users/models.py
from django.db import models

# Create your models here.

LearnLogs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

LearnLogs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


# Create your views here.
def index(request):
    """The homepage of the LearnLogs"""
    return render(request, 'LearnLogs/index.html')


@login_required
def topics(request):
    """The page shows all the topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'LearnLogs/topics.html', context)


@login_required
def topic(request, topic_id):
    """The page shows one topic and its all entries """
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {
        'topic': topic,
        'entries': entries,
    }
    return render(request, 'LearnLogs/topic.html', context)


@login_required
def new_topic(request):
    """The page is used to add new topic"""
    if request.method != 'POST':
        # No submitted datas, create a new form
        form = TopicForm()
    else:
        # progress with the posted datas
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('LearnLogs:topics'))

    context = {'form': form}
    return render(request, 'LearnLogs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """The page is used to add a new entry for a topic"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No submitted datas, create a new form
        form = EntryForm()
    else:
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(
                reverse('LearnLogs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'LearnLogs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('LearnLogs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'LearnLogs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, login, authenticate
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('LearnLogs:index'))


def register(request):
    """Register a new user"""
    if request.method != 'POST':
        """Show an empty form"""
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # login automatically, region to the index home page
            authenticated_user = authenticate(
                username=new_user.username, password=request.POST['passwordl'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('LearnLogs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

LearnLogs/templates/LearnLogs/base.html
<p>
  <a href="{% url 'LearnLogs:index' %}">LearnLongs HomePage</a>-
  <a href="{% url 'LearnLogs:topics' %}">Topics</a>-

  {% if user.is_authenticated %}
  Hello, {{user.username}}.
  <a href="{% url 'users:logout' %}">logout</a>
  {% else %}
  <a href="{% url 'users:register' %}">register</a>-
  <a href="{% url 'users:login' %}">login</a>
  {% endif %}
</p>

{% block content %}{% endblock content %}

LearnLogs/templates/LearnLogs/edit_entry.html
{% extends "LearnLogs/base.html" %}

{% block content %}

<p>
  <a href="{% url 'LearnLogs:topic' topic.id}">{{topic}}</a>
</p>

<p>Edit entry:</p>

<form action="{% url 'LearnLogs:edit_entry' entry.id %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button name="submit">save changes</button>
</form>

{% endblock content %}

LearnLogs/templates/LearnLogs/index.html
{% extends "LearnLogs/base.html" %}

{% block content %}

<p>Learning Logs help you keep track of your learning, for
  any topic you're learning about.
</p>
{% endblock content %}

LearnLogs/templates/LearnLogs/new_entry.html
{% extends "LearnLogs/base.html" %}

{% block content %}

<p>
  <a href="{% url 'LearnLogs:topic' topic.id %}">{{topic}}</a>
</p>

<p>Add a new entry:</p>
<form action="{url 'LearnLogs:new_entry' topic.id %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button name="submit">add entry</button>
</form>

{% endblock content %}

LearnLogs/templates/LearnLogs/new_topic.html
{% extends "LearnLogs/base.html" %}

{% block content %}

<p>Add a new topic:</p>

<form action="{% url 'LearnLogs:new_topic' %}" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button name="submit">add topic</button>
</form>

{% endblock content %}

LearnLogs/templates/LearnLogs/topic.html
{% extends 'LearnLogs/base.html' %}

{% block content %}

<p>{{topic}}</p>

<p>Entries:</p>
<p>
  <a href="{% url 'LearnLogs:new_entry' topic.id %}">add a new entry</a>
</p>

<ul>
  {% for entry in entries %}
  <li>
    <p>{{entry.date_added|date:'M d, Y H:i'}}</p>
    <p>{{entry.text|linebreaks}}</p>
    <p>
      <a href="{% url 'LearnLogs:edit_entry' entry.id %}">edit entry</a>
    </p>
  </li>
  {% empty %}
  <li>
    There are no entries for this topic.
  </li>
  {% endfor %}
</ul>

{% endblock content %}

LearnLogs/templates/LearnLogs/topics.html
{% extends "LearnLogs/base.html" %}

{% block content %}

<p>Topics</p>

<ul>
  {% for topic in topics %}
  <li>
    <a href="{% url 'LearnLogs:topic' topic.id %}">{{topic}}</a>
  </li>
  {% empty %}
  <li>No topics have been added yet.</li>
  {% endfor %}
</ul>
<a href="{% url 'LearnLogs:new_topic' %}">Add a new topic:</a>

{% endblock content %}

users/templates/users/login.html
{% extends "LearnLogs/base.html" %}

{% block content %}

{% if form.error %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="POST" action="{% url 'users:login' %}">
  {% csrf_token %}
  {{form.as_p}}
  <button name="submit">login</button>
  <input type="hidden" name="next" value="{% url 'LearnLogs:index' %}">
</form>

{% endblock content %}

users/templates/users/register.html
{% extends "LearnLogs/base.html" %}

{% block content %}
<form method="POST" action="{% url 'users:register' %}">
  {% csrf_token %}
  {{form.as_p}}
  <button name="submit">register</button>
  <input type="hidden" name="next" value="{% url 'LearnLogs:index' %}">
</form>

{% endblock content %}